MurmurationsNetwork/MurmurationsServices

- common/httputil/httputil.go
- services/index/internal/service/node_service.go
> feat: Only delete profile if it no longer exists at node's profileUrl

- charts/murmurations/templates/index-es/config.yaml
- charts/murmurations/templates/index-es/dpl.yaml
- charts/murmurations/templates/index-kibana/config.yaml
- charts/murmurations/templates/index-kibana/dpl.yaml
- charts/murmurations/templates/index-mongo/config.yaml
- charts/murmurations/templates/index/config.yaml
- charts/murmurations/templates/index/dpl.yaml
- charts/murmurations/templates/validation/config.yaml
- charts/murmurations/templates/validation/dpl.yaml
> chore: configurations and secrets

- charts/murmurations/templates/cronjob/config.yaml
- charts/murmurations/templates/index-es/dpl.yaml
- charts/murmurations/templates/index/config.yaml
- charts/murmurations/templates/validation/config.yaml
- services/validation/internal/service/validation_service.go
> chore: use schemaName instead of URLs

- services/validation/internal/service/validation_service_test.go
I don't think we need to create a test config. We can manually change them in the tests and it's much flexible.
resolves #5
resolves #53
> chore: change env manually in test

- charts/murmurations/charts/core/templates/ingress/ingress.yaml
- common/backoff/backoff.go
- common/elastic/client_interface.go
- common/mongo/client.go
- common/nats/client_interface.go
- services/index/internal/controller/event/listeners.go
- services/validation/internal/controller/event/listeners.go
- services/validation/internal/service/validation_service.go
> feat: exponential backoff

- .doc/create-secrets.md
- .doc/ingress-nginx.md
- .doc/secrets.md
- README.md
- charts/murmurations/charts/index/templates/index/config.yaml
- charts/murmurations/charts/index/templates/index/dpl.yaml
- charts/murmurations/charts/index/templates/mongo/dpl.yaml
- charts/murmurations/charts/library/templates/library/config.yaml
- charts/murmurations/charts/library/templates/library/dpl.yaml
- charts/murmurations/charts/library/templates/mongo/dpl.yaml
- charts/murmurations/charts/nodecleaner/templates/nodecleaner/config.yaml
- charts/murmurations/charts/nodecleaner/templates/nodecleaner/cronjob.yaml
- charts/murmurations/charts/schemaparser/templates/schemaparser/config.yaml
- charts/murmurations/charts/schemaparser/templates/schemaparser/cronjob.yaml
- common/dateutil/dateutil_test.go
- common/mongo/client.go
- common/mongo/client_interface.go
- common/mongo/mock_client.go
- common/mongo/util.go
- common/mongo/util_test.go
- services/cronjob/nodecleaner/cmd/nodecleaner/main.go
- services/cronjob/nodecleaner/config/config.go
- services/cronjob/nodecleaner/internal/adapter/mongodb/mongodb.go
- services/cronjob/nodecleaner/internal/repository/db/db.go
- services/cronjob/nodecleaner/internal/service/node_service.go
- services/cronjob/schemaparser/config/config.go
- services/cronjob/schemaparser/internal/adapter/mongodb/mongodb.go
- services/index/config/config.go
- services/library/config/config.go
- services/library/internal/adapter/mongodb/mongodb.go
resolves #72 
@geoffturk Could you try if you can run it locally by following the README?
> create k8s secrets

- .doc/access-application.md
- .doc/create-pvc.md
- .doc/ingress-nginx.md
- .doc/remove-completed-jobs.md
- charts/murmurations/charts/index/templates/mongo/dpl.yaml
- charts/murmurations/charts/library/templates/mongo/dpl.yaml
resolves #73
Delete the MongoDB and see if the data it's still there.
```
k delete pod/index-mongo-6895d76765-g9sqc
k delete pod/library-66677c7f8c-jdq6c
```
> feat: add pvc

- .doc/access-application.md
- .doc/efk/README.md
- .doc/efk/fluentd-config.yaml
- .doc/efk/values-elastic.yaml
- .doc/efk/values-fluentd.yaml
- .doc/efk/values-kibana.yaml
- .doc/logs.md
- charts/murmurations/charts/index/templates/mongo/dpl.yaml
- charts/murmurations/charts/library/templates/mongo/dpl.yaml
- services/validation/internal/service/validation_service.go
Only need to review `services/validation/internal/service/validation_service.go`, other files are documentations.
> fix: add more loggings

- charts/murmurations/charts/index/templates/es/dpl.yaml
- services/index/internal/app/application.go
- services/library/internal/app/application.go
- services/validation/internal/app/application.go
resolves #83
`k describe pod/index-es-cluster-0` and see if the data is still inside the elastic search.
> feat: add volume for elastic search

- services/cronjob/schemaparser/internal/service/schema_service.go
- services/cronjob/schemaparser/internal/service/schema_service_test.go
> fix schema parser:  parse string time error

- .doc/efk/README.md
- .doc/efk/fluentd-config.yaml
- .doc/efk/values-elasticsearch.yaml
- .doc/efk/values-kibana.yaml
- .doc/ingress-nginx/README.md
- .doc/ingress-nginx/values-ingress-nginx.yaml
- README.md
> fix: log client ip

- .doc/metrics-server.md
- .github/workflows/staging-geoip.yaml
- .github/workflows/staging-index.yaml
- .github/workflows/staging-library.yaml
- .github/workflows/staging-nodecleaner.yaml
- .github/workflows/staging-revalidatenode.yaml
- .github/workflows/staging-schemaparser.yaml
- .github/workflows/staging-validation.yaml
- charts/murmurations/charts/geoip/templates/geoip/dpl.yaml
- charts/murmurations/charts/index/templates/es/dpl.yaml
- charts/murmurations/charts/index/templates/index/dpl.yaml
- charts/murmurations/charts/index/templates/kibana/dpl.yaml
- charts/murmurations/charts/index/templates/mongo/dpl.yaml
- charts/murmurations/charts/library/templates/library/dpl.yaml
- charts/murmurations/charts/library/templates/mongo/dpl.yaml
- charts/murmurations/charts/message-queue/templates/nats/dpl.yaml
- charts/murmurations/charts/validation/templates/validation/dpl.yaml
> feat: setting the right requests and limits

- services/validation/internal/service/validation_service.go
@maxsarratt We'll need this once the semver changes have been made live in staging (and eventually main too) branch of the library repo.
> chore: update default schema name with semver

- .github/workflows/staging-index.yaml
- .github/workflows/staging-library.yaml
Reverts MurmurationsNetwork/MurmurationsServices#198
> Revert "prolong staging-index and staging-library execution time"

- e2e-tests.json
> test: improve and consolidate E2E tests

- .doc/db-es-updating-issue-217.md
- charts/murmurations/charts/nodecleaner/templates/nodecleaner/config.yaml
- charts/murmurations/charts/nodecleaner/templates/nodecleaner/cronjob.yaml
- common/constant/nodestatus.go
- common/elastic/client.go
- common/elastic/client_interface.go
- common/elastic/mock_client.go
- e2e-tests.json
- services/cronjob/nodecleaner/cmd/nodecleaner/main.go
- services/cronjob/nodecleaner/config/config.go
- services/cronjob/nodecleaner/global/init.go
- services/cronjob/nodecleaner/internal/entity/query/query_dao.go
- services/cronjob/nodecleaner/internal/entity/query/query_entity.go
- services/cronjob/nodecleaner/internal/repository/db/db.go
- services/cronjob/nodecleaner/internal/service/node_service.go
- services/index/global/init.go
- services/index/internal/adapter/controller/http/node_vo.go
- services/index/internal/adapter/repository/db/db.go
- services/index/internal/adapter/repository/db/node_mock.go
- services/index/internal/entity/query/query_dao.go
- services/index/internal/entity/query/query_entity.go
- services/index/internal/usecase/node_usecase.go
> feat: add 'deleted' status to index

- .doc/db-es-updating-issue-227.md
- charts/murmurations/Chart.yaml
- charts/murmurations/charts/geoip/Chart.yaml
- charts/murmurations/charts/index/Chart.yaml
- charts/murmurations/charts/index/templates/index/config.yaml
- charts/murmurations/charts/ingress/Chart.yaml
- charts/murmurations/charts/library/Chart.yaml
- charts/murmurations/charts/message-queue/Chart.yaml
- charts/murmurations/charts/nodecleaner/Chart.yaml
- charts/murmurations/charts/revalidatenode/Chart.yaml
- charts/murmurations/charts/schemaparser/Chart.yaml
- charts/murmurations/charts/validation/Chart.yaml
- common/tagsfilter/tagsfilter.go
- e2e-tests.json
- go.mod
- go.sum
- services/index/config/config.go
- services/index/global/init.go
- services/index/internal/adapter/repository/db/db.go
- services/index/internal/entity/query/query_dao.go
- services/index/internal/entity/query/query_entity.go
> feat: store & query by tags

- services/validation/internal/service/validation_service.go
> feat: use new default schema

- e2e-tests.json
- services/index/internal/adapter/controller/http/node_handler.go
- services/index/internal/app/url_mappings.go
> add nodes-sync

- charts/murmurations/charts/index/templates/index/config.yaml
- e2e-tests.json
- services/index/config/config.go
- services/index/internal/adapter/controller/http/node_handler.go
- services/index/internal/app/url_mappings.go
> feat: add profile validation endpoint

- .doc/db-es-updating-issue-238.md
- common/validateurl/validateurl.go
- common/validateurl/validateurl_test.go
- e2e-tests.json
- services/index/global/init.go
- services/index/internal/adapter/repository/db/db.go
- services/index/internal/entity/query/query_dao.go
- services/index/internal/entity/query/query_entity.go
> feat: store and query by primary_url

- .doc/postman-update-instruction.md
- e2e-tests.json
- services/index/internal/adapter/controller/http/node_handler.go
> test: add numbering to tests, shorten time of nodes-sync posting check

- common/elastic/query.go
- e2e-tests.json
- services/index/internal/entity/query/query_dao.go
> feat: multi-version schema search using semver wildcards

- .doc/ingress-nginx/README.md
- .github/workflows/main.yaml
- .github/workflows/pretest.yaml
- .github/workflows/test.yaml
- charts/murmurations/charts/index/templates/es/dpl.yaml
- charts/murmurations/charts/index/templates/index/config.yaml
- charts/murmurations/charts/ingress/templates/ingress/ingress.yaml
- charts/murmurations/charts/library/templates/library/config.yaml
- charts/murmurations/charts/nodecleaner/templates/nodecleaner/config.yaml
- charts/murmurations/charts/nodecleaner/templates/nodecleaner/cronjob.yaml
- charts/murmurations/charts/revalidatenode/templates/revalidatenode/cronjob.yaml
- charts/murmurations/charts/schemaparser/templates/schemaparser/config.yaml
- charts/murmurations/charts/schemaparser/templates/schemaparser/cronjob.yaml
- charts/murmurations/charts/validation/templates/validation/config.yaml
- skaffold.yaml
> chore: migrating to test branch from staging branch

- .doc/backup/README.md
> docs: update velero docs

- .doc/logging-monitoring-alerting/README.md
- services/cronjob/schemaparser/cmd/schemaparser/main.go
- services/cronjob/schemaparser/internal/domain/schema.go
> docs: add version to logging services

- .doc/logging-monitoring-alerting/README.md
- .doc/logging-monitoring-alerting/grafana-logging.json
- .doc/logging-monitoring-alerting/prom-stack-values.yaml
- charts/murmurations/charts/ingress/templates/ingress/ingress.yaml
- e2e-tests.json
> docs: update logging docs

- .doc/logging-monitoring-alerting/README.md
- .doc/logging-monitoring-alerting/grafana-logging.json
- .doc/logging-monitoring-alerting/prom-stack-values.yaml
> docs: update logging services docs

- README.md
> docs: update readme instruction for preventing throttle warning

- .doc/logging-monitoring-alerting/README.md
- .doc/logging-monitoring-alerting/grafana-logging.json
- .doc/logging-monitoring-alerting/prom-stack-values.yaml
- README.md
> docs: upgrade logging services

- charts/murmurations/charts/index/templates/es/dpl.yaml
- charts/murmurations/charts/index/templates/kibana/dpl.yaml
> chore: upgrade elastic and kibana to 7.17.5

- .doc/deploy-services.md
- .github/workflows/main.yaml
- charts/murmurations/charts/dataproxy/templates/dataproxy/config.yaml
- charts/murmurations/charts/dataproxyrefresher/templates/dataproxyrefresher/config.yaml
- charts/murmurations/charts/dataproxyrefresher/templates/dataproxyrefresher/cronjob.yaml
- charts/murmurations/charts/dataproxyupdater/templates/dataproxyupdater/config.yaml
- charts/murmurations/charts/dataproxyupdater/templates/dataproxyupdater/cronjob.yaml
- charts/murmurations/charts/index/templates/es/dpl.yaml
- charts/murmurations/charts/index/templates/index/config.yaml
- charts/murmurations/charts/ingress/templates/ingress/ingress.yaml
- charts/murmurations/charts/library/templates/library/config.yaml
- charts/murmurations/charts/nodecleaner/templates/nodecleaner/config.yaml
- charts/murmurations/charts/nodecleaner/templates/nodecleaner/cronjob.yaml
- charts/murmurations/charts/revalidatenode/templates/revalidatenode/cronjob.yaml
- charts/murmurations/charts/schemaparser/templates/schemaparser/config.yaml
- charts/murmurations/charts/schemaparser/templates/schemaparser/cronjob.yaml
- charts/murmurations/charts/validation/templates/validation/config.yaml
> refactor: update GitHub Actions files and remove old live env

- .github/workflows/pretest.yaml
- .github/workflows/test.yaml
> refactor: update CI/CD using Github flow

- services/dataproxy/cmd/seeder/main.go
> refactor: optimize importData function to reduce other server requests

- README.md
- common/elastic/client.go
- services/index/internal/entity/query/query_dao.go
> fix: fix inconsistent results returned with pagination

- common/pagination/pagination.go
- services/index/internal/adapter/repository/db/db.go
> refactor: change no result response to be consistent with response with results

- charts/murmurations/charts/dataproxy/templates/dataproxy/config.yaml
- charts/murmurations/charts/index/templates/index/config.yaml
- charts/murmurations/charts/schemaparser/templates/schemaparser/config.yaml
- charts/murmurations/charts/validation/templates/validation/config.yaml
- common/countries/countries.go
> refactor: update cdn to temp-cdn URLs

- charts/murmurations/charts/ingress/templates/ingress/ingress.yaml
> refactor: add original cdn and test-cdn to ingress

- charts/murmurations/charts/dataproxy/templates/dataproxy/config.yaml
- charts/murmurations/charts/index/templates/index/config.yaml
- charts/murmurations/charts/ingress/templates/ingress/ingress.yaml
- charts/murmurations/charts/schemaparser/templates/schemaparser/config.yaml
- charts/murmurations/charts/validation/templates/validation/config.yaml
- common/countries/countries.go
> refactor: revert temp-cdn to cdn

- services/cronjob/dataproxyupdater/cmd/dataproxyupdater/main.go
> refactor: skip over KVM profile parsing errors

- charts/murmurations/charts/ingress/templates/ingress/ingress.yaml
> refactor: remove CDN ingress

- services/cronjob/schemaparser/cmd/schemaparser/main.go
> refactor: delay Schemaparser for five minutes to ensure the schema list is up to date

- charts/murmurations/charts/library/templates/library/dpl.yaml
> fix: fix livenessProbe in library-app

- common/jsonapi/jsonapi.go
> fix: fix the page links with page parameter

- README.md
> fix: update the broken badge in the README

- common/elastic/client.go
- common/elastic/client_interface.go
- common/elastic/mock_client.go
- common/jsonapi/jsonapi.go
- e2e-tests.json
- services/index/internal/adapter/controller/http/node_handler.go
- services/index/internal/adapter/repository/db/db.go
- services/index/internal/adapter/repository/db/node_mock.go
- services/index/internal/app/url_mappings.go
- services/index/internal/entity/query/query_dao.go
- services/index/internal/entity/query/query_entity.go
- services/index/internal/usecase/node_usecase.go
> feat: add block search function

- common/elastic/client.go
- common/elastic/client_interface.go
- common/elastic/mock_client.go
- common/pagination/pagination.go
- e2e-tests.json
- services/index/internal/adapter/controller/http/node_handler.go
- services/index/internal/adapter/repository/db/db.go
- services/index/internal/adapter/repository/db/node_mock.go
- services/index/internal/app/url_mappings.go
- services/index/internal/entity/query/query_dao.go
- services/index/internal/entity/query/query_entity.go
- services/index/internal/usecase/node_usecase.go
> feat: add get-nodes endpoint for rendering in murmurationsMap

- common/elastic/query.go
- services/index/internal/entity/query/query_dao.go
> fix: fix node geolocation is empty error

- common/validateurl/validateurl.go
- common/validateurl/validateurl_test.go
> Fix primary_url processing when protocol is not specified

- .github/dependabot.yml
> chore: remove deleted branch from dependabot.yml

- services/cronjob/dataproxyrefresher/docker/Dockerfile-dev
- services/cronjob/dataproxyrefresher/docker/Dockerfile-prod
- services/cronjob/dataproxyupdater/docker/Dockerfile-dev
- services/cronjob/dataproxyupdater/docker/Dockerfile-prod
- services/cronjob/nodecleaner/docker/Dockerfile-dev
- services/cronjob/nodecleaner/docker/Dockerfile-prod
- services/cronjob/revalidatenode/docker/Dockerfile-dev
- services/cronjob/revalidatenode/docker/Dockerfile-prod
- services/cronjob/schemaparser/docker/Dockerfile-dev
- services/cronjob/schemaparser/docker/Dockerfile-prod
- services/dataproxy/docker/Dockerfile-dev
- services/dataproxy/docker/Dockerfile-prod
- services/geoip/docker/Dockerfile-dev
- services/geoip/docker/Dockerfile-prod
- services/index/docker/Dockerfile-dev
- services/index/docker/Dockerfile-prod
- services/library/docker/Dockerfile-dev
- services/library/docker/Dockerfile-prod
- services/validation/docker/Dockerfile-dev
- services/validation/docker/Dockerfile-prod
> Upgrade go to 19.5

- .github/workflows/main.yaml
- .github/workflows/test.yaml
Fix failed action job from #422
> Modify Github workflow file

- services/dataproxy/internal/controller/http/batches_handler.go
- services/dataproxy/internal/entity/batch.go
- services/dataproxy/internal/repository/db/batch_db.go
- services/dataproxy/internal/usecase/batch_usecase.go
- tests/e2e-tests.json
> Get user batches needs to response with batch title

- common/httputil/httputil.go
- services/index/internal/usecase/node_usecase.go
- services/validation/internal/service/validation_service.go
> Check profile_hash before changing last_updated

- .doc/secrets.md
- .github/workflows/test.yaml
- charts/murmurations/charts/schemaparser/templates/schemaparser/config.yaml
- common/httputil/httputil.go
- services/cronjob/schemaparser/cmd/schemaparser/main.go
- services/cronjob/schemaparser/config/config.go
- services/cronjob/schemaparser/internal/domain/schema.go
- services/cronjob/schemaparser/internal/service/schema_service.go
- services/cronjob/schemaparser/internal/service/schema_service_test.go
- tests/e2e-tests.json
> Update schema-parser to retrieve data from GitHub API directly

- common/countries/countries_test.go
- go.mod
- go.sum
- services/cronjob/schemaparser/internal/domain/schema.go
- services/cronjob/schemaparser/internal/service/schema_service.go
- services/library/internal/repository/db/schema.go
> Fix properties order in Library service

- charts/murmurations/charts/index/templates/index/config.yaml
- charts/murmurations/charts/nodecleaner/templates/nodecleaner/config.yaml
- common/dateutil/dateutil.go
- common/dateutil/dateutil_test.go
- services/cronjob/nodecleaner/cmd/nodecleaner/main.go
- services/cronjob/nodecleaner/config/config.go
- services/cronjob/nodecleaner/internal/service/node_service.go
- services/index/config/config.go
- services/index/internal/adapter/controller/http/node_handler.go
> Add index removal time to deleted status response

- charts/murmurations/charts/nodecleaner/templates/nodecleaner/config.yaml
- services/cronjob/nodecleaner/config/config.go
- services/cronjob/nodecleaner/internal/service/node_service.go
> Update the Time-to-Live (TTL) values in the nodecleaner service to make them readable

- skaffold.yaml
> chore: Upgrade Skaffold to latest version

- pkg/httputil/httputil.go
- services/index/internal/adapter/controller/rest/node_dto.go
- services/index/internal/usecase/node_usecase.go
> refactor: ignore redirected `profile_url`s

- services/cronjob/schemaparser/internal/service/schema_service.go
> feat: Improve SchemaParser Loading Speed

- .github/workflows/test.yaml
- build/index/docker/Dockerfile-prod
- docs/db-es-updating/issue-517.md
- services/index/cmd/esseeder/main.go
- services/index/global/init.go
- services/index/internal/adapter/controller/rest/node_handler.go
- services/index/internal/entity/query/query_dao.go
- services/index/internal/entity/query/query_entity.go
> feat: add `name` field to index

- .golangci.yml
- pkg/elastic/client.go
- pkg/elastic/constant.go
- pkg/mongo/client.go
> refactor: fix deprecated elastic type and mongo mergeOptions

- pkg/countries/countries.go
- pkg/validateurl/validateurl.go
- services/index/internal/model/export_test.go
- services/index/internal/model/node.go
- services/index/internal/model/node_test.go
- services/index/internal/model/nodes.go
- services/index/internal/model/profile.go
- services/index/internal/model/profile_test.go
- services/index/internal/service/node.go
- services/index/internal/service/node_test.go
> refactor: clean up SetNodeValid logic

- services/index/internal/controller/event/listeners.go
- services/validation/internal/controller/event/listeners.go
> fix: make sure always acknowledge NATS's message event

- services/cronjob/schemaparser/internal/model/schema.go
- services/cronjob/schemaparser/internal/schemaparser/parser.go
- services/cronjob/schemaparser/internal/schemaparser/parser_test.go
- services/cronjob/schemaparser/internal/service/schema.go
> fix: schemaParser not picking up title/description overrides

- charts/murmurations/charts/dataproxyrefresher/templates/dataproxyrefresher/cronjob.yaml
- charts/murmurations/charts/dataproxyupdater/templates/dataproxyupdater/cronjob.yaml
- charts/murmurations/charts/nodecleaner/templates/nodecleaner/cronjob.yaml
- charts/murmurations/charts/revalidatenode/templates/revalidatenode/cronjob.yaml
- charts/murmurations/charts/schemaparser/templates/schemaparser/cronjob.yaml
Hope this configuration can reduce our memory consumption. We should keep an eye on the memory usage.
Part of #552
> Configure CronJob retry and cleanup settings

- services/index/internal/model/export_test.go
- services/index/internal/model/profile.go
- services/index/internal/model/profile_test.go
> feat: Remove non-indexed fields before sending JSON to ES

- charts/murmurations/charts/dataproxy/templates/dataproxy/dpl.yaml
- charts/murmurations/charts/dataproxy/templates/mongo/dpl.yaml
- charts/murmurations/charts/geoip/templates/geoip/dpl.yaml
- charts/murmurations/charts/index/templates/index/dpl.yaml
- charts/murmurations/charts/index/templates/kibana/dpl.yaml
- charts/murmurations/charts/index/templates/mongo/dpl.yaml
- charts/murmurations/charts/library/templates/library/dpl.yaml
- charts/murmurations/charts/library/templates/mongo/dpl.yaml
- charts/murmurations/charts/message-queue/templates/nats/dpl.yaml
- charts/murmurations/charts/schemaparser/templates/redis/dpl.yaml
- charts/murmurations/charts/validation/templates/validation/dpl.yaml
> fix: set revisionHistoryLimit to clean up old replicasets

- .github/workflows/test.yaml
> chore: bump node version for newman

- services/index/internal/model/profile.go
- services/index/internal/model/profile_test.go
> fix: skip zero values if geo or lat/lon fields are absent

- .github/workflows/test.yaml
remove `npm install` to see if that works.
> fix: e2e test error in CI

- cmd/schemaparser/main.go
- pkg/httputil/httputil.go
- pkg/logger/logger.go
- services/cronjob/schemaparser/README.md
- services/cronjob/schemaparser/internal/schemaparser/parser.go
- services/cronjob/schemaparser/internal/schemaparser/parser_test.go
- services/cronjob/schemaparser/internal/service/schema.go
- services/cronjob/schemaparser/pkg/schemaparser/cronjob.go
1. Make sure the schemaparser service logs an error (originally, it would always log "Schemas were loaded successfully").
2. Add the schemaparser documentation.
> refactor: enhance schemaparser parsing logic

- docs/backup/velero-deployment.patch.yaml
> config: update velero YAML files

- charts/murmurations/charts/revalidatenode/templates/revalidatenode/cronjob.yaml
- cmd/revalidatenode/main.go
- services/cronjob/revalidatenode/config/config.go
- services/cronjob/revalidatenode/internal/model/node.go
- services/cronjob/revalidatenode/internal/repository/mongo/node.go
- services/cronjob/revalidatenode/internal/service/node.go
- services/cronjob/revalidatenode/pkg/revalidatenode/cronjob.go
> fix: refactor and set cpu limit for revalidatenode

- charts/murmurations/charts/nodecleaner/templates/nodecleaner/cronjob.yaml
- cmd/nodecleaner/main.go
- services/cronjob/nodecleaner/internal/repository/es/es.go
- services/cronjob/nodecleaner/internal/repository/mongo/node.go
- services/cronjob/nodecleaner/internal/service/node.go
- services/cronjob/nodecleaner/pkg/nodecleaner/cronjob.go
> fix: refactor and set cpu limit for nodecleaner

- charts/murmurations/charts/dataproxyrefresher/templates/dataproxyrefresher/cronjob.yaml
- charts/murmurations/charts/dataproxyupdater/templates/dataproxyupdater/cronjob.yaml
> fix: limit cpu usage for dataproxy refresher & updater

- pkg/event/base_publisher.go
- services/cronjob/revalidatenode/internal/service/node.go
> fix: make revalidation synchronous

- services/index/internal/controller/rest/node_handler.go
> fix: return 404 when deleting a non-existent node

- services/index/internal/service/node.go
> fix: limit profile_url length to 2000 characters

- .github/workflows/pr.yaml
- Makefile
- build/dataproxyrefresher/mk/Makefile
- build/geoip/mk/Makefile
- build/index/mk/Makefile
- build/library/mk/Makefile
- build/nodecleaner/mk/Makefile
- build/revalidatenode/mk/Makefile
- build/schemaparser/mk/Makefile
- build/validation/mk/Makefile
- pkg/jsonapi/jsonapi.go
- pkg/jsonapi/jsonapi_test.go
- services/cronjob/dataproxyupdater/Makefile
- services/dataproxy/Makefile
> feat: Use https in links

- test/e2e-tests-staging.json
> test: add more e2e tests

- .github/workflows/main.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- build/README.md
- build/dataproxy/docker/Dockerfile
- build/dataproxy/docker/Dockerfile-dev
- build/dataproxyrefresher/docker/Dockerfile
- build/dataproxyrefresher/docker/Dockerfile-dev
- build/dataproxyupdater/docker/Dockerfile
- build/dataproxyupdater/docker/Dockerfile-dev
- build/geoip/docker/Dockerfile
- build/geoip/docker/Dockerfile-dev
- build/index/docker/Dockerfile
- build/index/docker/Dockerfile-dev
- build/library/docker/Dockerfile
- build/library/docker/Dockerfile-dev
- build/nodecleaner/docker/Dockerfile
- build/nodecleaner/docker/Dockerfile-dev
- build/revalidatenode/docker/Dockerfile
- build/revalidatenode/docker/Dockerfile-dev
- build/schemaparser/docker/Dockerfile
- build/schemaparser/docker/Dockerfile-dev
- build/validation/docker/Dockerfile
- build/validation/docker/Dockerfile-dev
- docs/dot-github-directory.md
- go.mod
- go.sum
> build(deps): bump go from 1.19 to 1.21

- README.md
- docs/rancher/README.md
- docs/rancher/backing-up-rancher.md
> chore(doc): add backing-up-rancher

- docs/rancher/README.md
- docs/rancher/how-to-create-alerts.md
> chore(doc): add how-to-create-alerts.md

- services/index/internal/controller/rest/node_handler.go
- services/index/internal/index/errors.go
- services/index/internal/service/node.go
- skaffold.yaml
> chore: Better Error Logging

- services/dataproxyupdater/internal/model/update.go
- services/dataproxyupdater/internal/repository/mongo/update.go
- services/dataproxyupdater/internal/service/update.go
- services/dataproxyupdater/pkg/dataproxyupdater/service.go
> Check it again and eliminate the errors if there is an API glitch

- services/dataproxy/internal/service/batch.go
- services/dataproxy/internal/service/batch_test.go
- services/dataproxyupdater/pkg/dataproxyupdater/service.go
> Enable CSV batch upload to process arrays within a field

- charts/murmurations/charts/dataproxyrefresher/templates/dataproxyrefresher/config.yaml
- charts/murmurations/charts/dataproxyupdater/templates/dataproxyupdater/config.yaml
- charts/murmurations/charts/index/templates/index/config.yaml
- charts/murmurations/charts/library/templates/library/config.yaml
- charts/murmurations/charts/nodecleaner/templates/nodecleaner/config.yaml
- charts/murmurations/charts/revalidatenode/templates/revalidatenode/config.yaml
- charts/murmurations/charts/schemaparser/templates/schemaparser/config.yaml
- charts/murmurations/charts/validation/templates/validation/config.yaml
- services/index/internal/controller/rest/node_handler.go
> Handle timeout error cleanly when trying to delete a node on a non-existent server

- pkg/httputil/httputil.go
- services/index/internal/controller/rest/request.go
- services/index/internal/controller/rest/request_test.go
- services/index/internal/service/node.go
This reverts commit 1f77e8a4d6715fac86331c1627b453970281edc1.
Resolved #762
> Revert "refactor: ignore redirected `profile_url`s (#518)"

- docs/testing-schemas-in-local.md
> Add documentation for local deployment of the schema

- services/dataproxyrefresher/pkg/fresher/service.go
> Prevent dataproxyrefresher Failure Due to External API Errors

- services/index/internal/service/node.go
> fix: reindexing issue after node deletion and re-addition in Elasticsearch

- charts/murmurations/charts/schemaparser/templates/schemaparser/cronjob.yaml
- services/schemaparser/internal/service/schema.go
- services/schemaparser/pkg/schemaparser/cronjob.go
> refactor: Log error messages into Redis

- docs/testing/simulate-offline-services.md
> docs: explain service failure testing mechanism

- test/e2e-tests-staging.json
> Fix e2e tests for non-existent-profile url

- .github/workflows/test.yaml
- pkg/mongo/client.go
- pkg/mongo/client_interface.go
- pkg/mongo/mock_client.go
- services/dataproxy/global/init.go
> Introduce Indexing for Profile Table in Data-Proxy Service

- services/revalidatenode/internal/service/node.go
> Fix duplicate triggering of nodeCreated events

- services/index/internal/controller/rest/node_handler.go
- services/index/internal/service/node.go
- services/nodecleaner/internal/repository/mongo/node.go
- services/validation/internal/service/validation.go
- test/e2e-tests-staging.json
> Handle expires_at as expires

- pkg/profile/profilehasher/profilehasher.go
- services/index/internal/service/node.go
> Fix duplicate profile requests in Index service
